apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-change-operator
  namespace: git-change-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-change-operator-manager-role
  namespace: git-change-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits
  - pullrequests
  - gitchangeoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits/finalizers
  - pullrequests/finalizers
  - gitchangeoperators/finalizers
  verbs:
  - update
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits/status
  - pullrequests/status
  - gitchangeoperators/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-change-operator-manager-rolebinding
  namespace: git-change-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-change-operator-manager-role
subjects:
- kind: ServiceAccount
  name: git-change-operator
  namespace: git-change-operator-system