apiVersion: v1
kind: Secret
metadata:
  name: github-auth
  namespace: default
type: Opaque
data:
  token: <base64-encoded-github-token>
---
apiVersion: gco.galos.one/v1
kind: GitCommit
metadata:
  name: example-commit
  namespace: default
spec:
  repository: https://github.com/owner/repo.git
  branch: main
  commitMessage: "Update configuration files"
  authSecretRef: github-auth
  authSecretKey: token
  files:
  - path: config/app.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: app-config
      data:
        setting: value
  - path: README.md
    content: |
      # Updated README
      
      This file was updated by the git-change-operator.