apiVersion: gco.galos.one/v1
kind: GitChangeOperator
metadata:
  name: git-change-operator-sample
  namespace: git-change-operator-system
spec:
  replicaCount: 1
  image:
    repository: ghcr.io/mihaigalos/git-change-operator
    tag: latest
    pullPolicy: IfNotPresent
  operator:
    leaderElect: true
    metricsAddr: ":8080"
    probeAddr: ":8081"
  rbac:
    create: true
  serviceAccount:
    create: true
    name: ""
  metrics:
    enabled: true
    service:
      type: ClusterIP
      port: 8080
    serviceMonitor:
      enabled: true
      name: git-change-operator-metrics
      interval: "30s"
      scrapeTimeout: "10s"
      labels:
        prometheus: kube-prometheus
      annotations:
        monitoring/scrape: "true"
  ingress:
    enabled: true
    name: git-change-operator-ingress
    ingressClassName: nginx
    labels:
      app: git-change-operator
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: git-change-operator.example.com
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: git-change-operator-metrics-service
                port:
                  number: 8080
    tls:
      - hosts:
          - git-change-operator.example.com
        secretName: git-change-operator-tls
  crds:
    install: true
status:
  phase: Ready
