{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "git-change-operator.clusterRoleName" . }}
  labels:
    {{- include "git-change-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits/finalizers
  verbs:
  - update
- apiGroups:
  - gco.galos.one
  resources:
  - gitcommits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gco.galos.one
  resources:
  - pullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gco.galos.one
  resources:
  - pullrequests/finalizers
  verbs:
  - update
- apiGroups:
  - gco.galos.one
  resources:
  - pullrequests/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.rbac.additionalReadPermissions.enableWildcard }}
# WARNING: Broad read permissions - NOT recommended for production
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
{{- else }}
# Specific read permissions for Kubernetes resources
{{- range .Values.rbac.additionalReadPermissions.specificPermissions }}
- apiGroups:
{{- range .apiGroups }}
  - {{ . | quote }}
{{- end }}
  resources:
{{- range .resources }}
  - {{ . | quote }}
{{- end }}
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}
{{- end }}