{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "git-change-operator.clusterRoleBindingName" . }}
  labels:
    {{- include "git-change-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "git-change-operator.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "git-change-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}